# Messy Employees Dataset Cleaning

In [85]:
# importing the libraries
import pandas as pd
import numpy as np
from pandas.core.groupby.grouper import Grouping
from pandas.core.resample import get_resampler_for_grouping

In [86]:
# Reading the file using Pandas
df =pd.read_csv('Messy_Employee_dataset.csv')
df.isnull().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

In [87]:
# Filling the NAN values in the age column by its median
# df['Age'] = df['Age'].interpolate(method='linear')
df['Age'] = df['Age'].fillna(df['Age'].mean(),inplace=True).astype(int)
df

C:\Users\user\AppData\Local\Temp\ipykernel_17984\1269670599.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'] = df['Age'].fillna(df['Age'].mean(),inplace=True).astype(int)

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,32,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,32,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False

In [88]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean() , inplace=True).astype(int)
df

C:\Users\user\AppData\Local\Temp\ipykernel_17984\2364458987.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Salary'] = df['Salary'].fillna(df['Salary'].mean() , inplace=True).astype(int)

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25,DevOps-California,Active,4/2/2021,59767,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,32,Finance-Texas,Active,7/10/2020,65304,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,32,Admin-Nevada,Pending,12/7/2023,88145,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,11/27/2021,69450,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,1/5/2022,109324,frank.williams@example.com,-1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30,HR-California,Active,8/19/2023,85155,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30,Cloud Tech-Texas,Inactive,11/7/2021,100215,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40,Finance-New York,Active,10/4/2023,114587,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30,HR-Florida,Inactive,12/16/2024,71318,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30,DevOps-Illinois,Pending,2/22/2021,77764,heidi.jones@example.com,-7629745492,Average,False

In [89]:
df.isnull().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

* Grouping

In [90]:
Grouping = df.groupby(['Employee_ID','First_Name','Last_Name','Department_Region'])['Salary'].sum()
Grouping

Employee_ID  First_Name  Last_Name  Department_Region
EMP1000      Bob         Davis      DevOps-California      59767
EMP1001      Bob         Brown      Finance-Texas          65304
EMP1002      Alice       Jones      Admin-Nevada           88145
EMP1003      Eva         Davis      Admin-Nevada           69450
EMP1004      Frank       Williams   Cloud Tech-Florida    109324
                                                           ...
EMP2015      David       Miller     HR-California          85155
EMP2016      David       Johnson    Cloud Tech-Texas      100215
EMP2017      Charlie     Williams   Finance-New York      114587
EMP2018      Alice       Garcia     HR-Florida             71318
EMP2019      Heidi       Jones      DevOps-Illinois        77764
Name: Salary, Length: 1020, dtype: int64

In [91]:
# Checking if there any infinite Values are Present
df.replace([np.inf, -np.inf], np.nan, inplace=True).sum()

Employee_ID          EMP1000EMP1001EMP1002EMP1003EMP1004EMP1005EMP1...
First_Name           BobBobAliceEvaFrankAliceFrankBobFrankCharlieDa...
Last_Name            DavisBrownJonesDavisWilliamsGarciaJonesJonesDa...
Age                                                              33032
Department_Region    DevOps-CaliforniaFinance-TexasAdmin-NevadaAdmi...
Status               ActiveActivePendingInactiveActiveInactiveActiv...
Join_Date            4/2/20217/10/202012/7/202311/27/20211/5/20226/...
Salary                                                        86857651
Email                bob.davis@example.combob.brown@example.comalic...
Phone                                                   -5041098018406
Performance_Score    AverageExcellentGoodGoodPoorGoodGoodAverageExc...
Remote_Work                                                        513
dtype: object

In [ ]:
# For Droping the duplicates if present

duplicate =df.duplicated().any()    # For Checking
duplicate

# df.drop_duplicates(inplace=True)   # For Droping

In [92]:
# For replacing the  nagetive salaries
"""
df['Salary'] =np.where(df['Salary'] < 0 , df['Salary'].mean() , df['Salary'] )
salary_mean = df['Salary'].mean()
salary_Std =  df['Salary'].std()
upper_bound = salary_mean - (3 * salary_Std)
lower_bound = salary_mean + (3 * salary_Std)
"""

# Removing rows where salaries are too high
"""
df = df[(df['Salary'] >= lower_bound) & (df['Salary'] <= upper_bound)]
"""

"\ndf['Salary'] =np.where(df['Salary'] < 0 , df['Salary'].mean() , df['Salary'] )\nsalary_mean = df['Salary'].mean()\nsalary_Std =  df['Salary'].std()\nupper_bound = salary_mean - (3 * salary_Std)\nlower_bound = salary_mean + (3 * salary_Std)\n"

In [80]:
# saving the file as csv
df.to_csv('cleaned_Project.csv',index=False)
df

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25,DevOps-California,Active,4/2/2021,59767,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,25,Finance-Texas,Active,7/10/2020,65304,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,25,Admin-Nevada,Pending,12/7/2023,88145,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,11/27/2021,69450,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,1/5/2022,109324,frank.williams@example.com,-1586734256,Poor,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30,HR-California,Active,8/19/2023,85155,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30,Cloud Tech-Texas,Inactive,11/7/2021,100215,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40,Finance-New York,Active,10/4/2023,114587,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30,HR-Florida,Inactive,12/16/2024,71318,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30,DevOps-Illinois,Pending,2/22/2021,77764,heidi.jones@example.com,-7629745492,Average,False